class Stringler {
  String _selected;

  List<Map> myJson = [
    {"id": '1', "image": "  images/netflix.png", "name": "Netflix"},
    {"id": '2', "image": "  images/spotify.png", "name": "Spotify"},
    {"id": '3', "image": "  images/youtube.png", "name": "Youtube Premium"},
    {"id": '4', "image": "  images/applemusic.png", "name": "Apple Music"},
    {"id": '5', "image": "  images/digiturk.png", "name": "Digiturk"},
    {"id": '6', "image": "  images/dsmart.png", "name": "D-Smart"},
    {"id": '7', "image": "  images/grammarly.png", "name": "Grammarly"},
    {"id": '8', "image": "  images/turksat.png", "name": "Türksat"},
    {"id": '9', "image": "  images/turktelekom.png", "name": "Türk Telekom"},
    {"id": '10', "image": "  images/turkcell.png", "name": "SuperOnline"},
    {"id": '11', "image": "  images/ttnet.png", "name": "TTNET"},
    {"id": '12', "image": "  images/bedas.png", "name": "BEDAŞ"},
    {"id": '13', "image": "  images/iski.jpg", "name": "İSKİ"},
    {"id": '14', "image": "  images/igdas.png", "name": "İGDAŞ"},
    {"id": '15', "image": "  images/puhutv.jpg", "name": "Puhu TV"},
    {"id": '16', "image": "  images/zomato.png", "name": "Zomato"},
    {"id": '17', "image": "  images/isbank.png", "name": "İş Bankası"},
    {"id": '18', "image": "  images/yapikredi.png", "name": "Yapı Kredi"},
    {"id": '19', "image": "  images/akbank.jpg", "name": "Akbank"},
    {"id": '20', "image": "  images/appletv.png", "name": "Apple TV"},

  ];

  static const List<String> UYG_ISIMLERI = [
    "Netflix",
    "Spotify",
    "Youtube Premium",
    "Apple Music",
    "Digiturk",
    "D-Smart",
    "Grammarly",
    "Türksat",
    "Türk Telekom",
    "SuperOnline",
    "TTNET",
    "BEDAŞ",
    "İSKİ",
    "İGDAŞ",
    "Puhu TV",
    "Zomato",
    "İş Bankası",
    "Yapı Kredi",
    "Akbank",
    "Apple TV",
  ];

  static const List<String> UYG_RESIMLERI = [
    "images/netflix.png",
    "images/spotify.png",
    "images/youtube.png",
    "images/applemusic.png",
    "images/digiturk.png",
    "images/dsmart.png",
    "images/grammarly.png",
    "images/turksat.png",
    "images/turktelekom.png",
    "images/turkcell.png",
    "images/ttnet.png",
    "images/bedas.png",
    "images/iski.jpg",
    "images/igdas.png",
    "images/puhutv.jpg",
    "images/zomato.png",
    "images/isbank.png",
    "images/yapikredi.png",
    "images/akbank.jpg",
    "images/appletv.png",
  ];

  static const List<String> AYLAR = [
    "Ocak",
    "Şubat",
    "Mart",
    "Nisan",
    "Mayıs",
    "Haziran",
    "Temmuz",
    "Ağustos",
    "Eylül",
    "Ekim",
    "Kasım",
    "Aralık",
  ];
}
